#!/usr/bin/env python3
"""Real SQL/HTTP/worker tests, using only a disposable private cluster."""
import concurrent.futures
import io
import json
import os
import select
import signal
import shutil
import subprocess
import sys
import tempfile
import threading
import unittest
import urllib.error
import urllib.request
from pathlib import Path
from http.server import ThreadingHTTPServer

# Keep generated bytecode out of the shared source and inherited test children.
sys.dont_write_bytecode = True
os.environ["PYTHONDONTWRITEBYTECODE"] = "1"

import db
import database
import worker
from web import Handler

SOURCE = Path(__file__).resolve().parent


class NotesTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.temp = tempfile.TemporaryDirectory(prefix="pn-", dir="/tmp")
        cls.previous_state = os.environ.get("P_NOTES_STATE")
        os.environ["P_NOTES_STATE"] = cls.temp.name
        cls.log = open(Path(cls.temp.name) / "postgres.log", "w+")
        cls.process = None
        try:
            cls.start_database()
            db.migrate()
            cls.server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
            cls.thread = threading.Thread(target=cls.server.serve_forever, daemon=True)
            cls.thread.start()
        except Exception:
            cls.stop_database()
            cls.log.seek(0)
            print(cls.log.read(), file=sys.stderr)
            cls.log.close()
            cls.temp.cleanup()
            cls.restore_env()
            raise

    @classmethod
    def restore_env(cls):
        if cls.previous_state is None:
            os.environ.pop("P_NOTES_STATE", None)
        else:
            os.environ["P_NOTES_STATE"] = cls.previous_state

    @classmethod
    def start_database(cls):
        cls.process = subprocess.Popen([sys.executable, str(SOURCE / "database.py"), "serve"],
                                       stdout=cls.log, stderr=cls.log)
        db.wait_ready()

    @classmethod
    def stop_database(cls):
        if cls.process and cls.process.poll() is None:
            cls.process.send_signal(signal.SIGINT)
            cls.process.wait(timeout=20)
        cls.process = None

    @classmethod
    def tearDownClass(cls):
        cls.server.shutdown()
        cls.server.server_close()
        cls.thread.join()
        cls.stop_database()
        cls.log.close()
        cls.temp.cleanup()
        cls.restore_env()

    def setUp(self):
        with db.connect() as conn:
            conn.execute("TRUNCATE jobs, notes RESTART IDENTITY")

    def request(self, path, body=None):
        url = f"http://127.0.0.1:{self.server.server_port}{path}"
        request = urllib.request.Request(url, data=None if body is None else json.dumps(body).encode(),
                                         headers={"Content-Type": "application/json"})
        try:
            response = urllib.request.urlopen(request, timeout=5)
        except urllib.error.HTTPError as error:
            response = error
        with response:
            return response.status, json.load(response)

    def test_http_and_word_count(self):
        self.assertEqual(self.request("/health")[0], 200)
        status, note = self.request("/notes", {"body": "hello\tprivate\nnotes"})
        self.assertEqual(status, 201)
        self.assertEqual(note["status"], "pending")
        self.assertTrue(worker.process_one())
        self.assertFalse(worker.process_one())
        note = self.request("/notes")[1]["notes"][0]
        self.assertEqual((note["status"], note["word_count"]), ("processed", 3))
        with db.connect() as conn:
            self.assertEqual(conn.execute("SELECT count(*) AS n FROM jobs WHERE completed_at IS NOT NULL").fetchone()["n"], 1)

    def test_validation_and_unknown_routes(self):
        for body in [None, "", "  ", 42, "x" * 10001]:
            self.assertEqual(self.request("/notes", {"body": body})[0], 400)
        self.assertEqual(self.request("/notes", ["bad"])[0], 400)
        self.assertEqual(self.request("/missing")[0], 404)
        self.assertEqual(db.list_notes(), [])

    def test_note_and_job_are_atomic(self):
        with db.connect() as conn:
            conn.execute("""CREATE FUNCTION refuse_sample_job() RETURNS trigger LANGUAGE plpgsql
                AS $$ BEGIN RAISE EXCEPTION 'injected queue failure'; END $$""")
            conn.execute("CREATE TRIGGER refuse_sample_job BEFORE INSERT ON jobs FOR EACH ROW EXECUTE FUNCTION refuse_sample_job()")
        try:
            self.assertEqual(self.request("/notes", {"body": "must roll back"})[0], 503)
            self.assertEqual(db.list_notes(), [])
        finally:
            with db.connect() as conn:
                conn.execute("DROP TRIGGER refuse_sample_job ON jobs")
                conn.execute("DROP FUNCTION refuse_sample_job()")

    def test_interrupted_worker_recovers(self):
        db.create_note("durable pending work")
        process = subprocess.Popen([sys.executable, str(SOURCE / "worker.py"), "--once", "--hold-before-commit", "30"],
                                   stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        try:
            readable, _, _ = select.select([process.stdout], [], [], 10)
            self.assertTrue(readable, "worker never opened its transaction")
            self.assertIn(b"transaction open", process.stdout.readline())
            process.kill()
            process.wait(timeout=10)
            note = db.list_notes()[0]
            self.assertEqual((note["status"], note["word_count"]), ("pending", None))
            self.assertTrue(worker.process_one())
            self.assertFalse(worker.process_one())
            self.assertEqual(db.list_notes()[0]["word_count"], 3)
        finally:
            if process.poll() is None:
                process.kill()
                process.wait(timeout=10)
            process.stdout.close()

    def test_concurrent_workers_finish_each_stored_result_once(self):
        for i in range(12):
            db.create_note(f"queued note {i}")
        def drain():
            while worker.process_one():
                pass
        with concurrent.futures.ThreadPoolExecutor(max_workers=3) as pool:
            list(pool.map(lambda _: drain(), range(3)))
        self.assertEqual(len(db.list_notes()), 12)
        self.assertTrue(all(n["word_count"] == 3 and n["status"] == "processed" for n in db.list_notes()))
        with db.connect() as conn:
            self.assertEqual(conn.execute("SELECT count(*) AS n FROM jobs WHERE completed_at IS NOT NULL").fetchone()["n"], 12)

    def test_database_restart_preserves_rows_jobs_and_reports_unavailability(self):
        db.create_note("accepted before restart")
        try:
            self.stop_database()
            self.assertEqual(self.request("/health")[0], 503)
            self.assertEqual(self.request("/notes", {"body": "refused while stopped"})[0], 503)
        finally:
            self.start_database()
        db.migrate()
        self.assertEqual(len(db.list_notes()), 1)
        self.assertEqual(db.list_notes()[0]["status"], "pending")
        self.assertTrue(worker.process_one())
        self.assertEqual(db.list_notes()[0]["word_count"], 3)

    def test_repeat_setup_preserves_cluster_and_schema(self):
        note = db.create_note("survives repeated setup")
        before = (db.state_dir() / "cluster/global/pg_control").read_bytes()
        database.initialize()
        db.migrate()
        self.assertEqual(db.list_notes()[0]["id"], note["id"])
        self.assertEqual((db.state_dir() / "cluster/global/pg_control").read_bytes(), before)
        with db.connect() as conn:
            self.assertEqual(conn.execute("SELECT count(*) AS n FROM jobs").fetchone()["n"], 1)

    def test_unknown_schema_refused_without_data_loss(self):
        db.create_note("future schema")
        with db.connect() as conn:
            conn.execute("UPDATE notes_schema SET version=999")
        try:
            with self.assertRaisesRegex(RuntimeError, "Unsupported notes schema"):
                db.migrate()
            self.assertEqual(db.list_notes()[0]["body"], "future schema")
            self.assertEqual(self.request("/health")[0], 503)
        finally:
            with db.connect() as conn:
                conn.execute("UPDATE notes_schema SET version=1")

    def test_damaged_schema_refused_without_repair_or_data_loss(self):
        note = db.create_note("retained through schema damage")
        # Renames make required objects unavailable while keeping their data
        # intact, so both refusal and absence of automatic repair are visible.
        damages = [
            ("ALTER TABLE jobs RENAME TO saved_jobs", "ALTER TABLE saved_jobs RENAME TO jobs", "required table jobs"),
            ("ALTER TABLE notes RENAME COLUMN word_count TO saved_word_count", "ALTER TABLE notes RENAME COLUMN saved_word_count TO word_count", "notes.word_count"),
            ("ALTER TABLE jobs ALTER COLUMN completed_at TYPE timestamp", "ALTER TABLE jobs ALTER COLUMN completed_at TYPE timestamptz USING completed_at AT TIME ZONE 'UTC'", "jobs.completed_at"),
        ]
        for damage, restore, message in damages:
            with self.subTest(damage=damage):
                with db.connect() as conn:
                    conn.execute(damage)
                try:
                    with self.assertRaisesRegex(db.SchemaError, message):
                        db.migrate()
                    status, payload = self.request("/health")
                    self.assertEqual(status, 503)
                    self.assertIn(message, payload["error"])
                    with db.connect() as conn:
                        self.assertEqual(conn.execute("SELECT version FROM notes_schema").fetchall(), [{"version": 1}])
                        self.assertEqual(conn.execute("SELECT id, body FROM notes").fetchall(), [{"id": note["id"], "body": note["body"]}])
                finally:
                    with db.connect() as conn:
                        conn.execute(restore)
                self.assertEqual(self.request("/health")[0], 200)
                self.assertEqual(db.list_notes(), [note])

    def test_schema_readiness_allows_extra_columns(self):
        note = db.create_note("retained with application extension")
        with db.connect() as conn:
            conn.execute("ALTER TABLE notes ADD COLUMN sample_extension text")
        try:
            db.migrate()
            self.assertEqual(self.request("/health")[0], 200)
            self.assertEqual(db.list_notes(), [note])
        finally:
            with db.connect() as conn:
                conn.execute("ALTER TABLE notes DROP COLUMN sample_extension")

    def test_private_socket_and_tcp_disabled(self):
        with db.connect() as conn:
            self.assertEqual(conn.execute("SHOW listen_addresses").fetchone()["listen_addresses"], "")
            self.assertEqual(conn.execute("SHOW unix_socket_permissions").fetchone()["unix_socket_permissions"], "0700")
        self.assertEqual((db.state_dir() / "socket").stat().st_mode & 0o777, 0o700)

    def test_damaged_or_incompatible_cluster_is_never_reinitialized(self):
        original = os.environ["P_NOTES_STATE"]
        try:
            with tempfile.TemporaryDirectory(prefix="pn-bad-", dir="/tmp") as temp:
                os.environ["P_NOTES_STATE"] = temp
                cluster = Path(temp) / "cluster"
                cluster.mkdir()
                (cluster / "do-not-erase").write_text("retained")
                with self.assertRaisesRegex(RuntimeError, "Damaged or uncertain"):
                    database.initialize()
                for name in ["PG_VERSION", "global/pg_control", "postgresql.conf", "pg_hba.conf"]:
                    target = cluster / name
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_text("999" if name == "PG_VERSION" else "fixture")
                (cluster / "base").mkdir()
                (cluster / "pg_wal").mkdir()
                with self.assertRaisesRegex(RuntimeError, "major mismatch"):
                    database.initialize()
                self.assertEqual((cluster / "PG_VERSION").read_text(), "999")
                self.assertEqual((cluster / "do-not-erase").read_text(), "retained")
        finally:
            os.environ["P_NOTES_STATE"] = original

    def test_installer_is_idempotent_and_does_not_enable(self):
        target = Path(self.temp.name) / "units"
        command = [sys.executable, str(SOURCE / "install.py"), "--no-reload", "--unit-dir", str(target)]
        subprocess.run(command, check=True, stdout=subprocess.DEVNULL)
        before = {p.name: p.read_text() for p in target.iterdir()}
        subprocess.run(command, check=True, stdout=subprocess.DEVNULL)
        self.assertEqual(before, {p.name: p.read_text() for p in target.iterdir()})
        self.assertEqual(len(before), 3)
        self.assertFalse((target / "default.target.wants").exists())
        self.assertIn("BindsTo=p-project-notes-db.service", before["p-project-notes-web.service"])
        self.assertIn(str(Path(sys.executable).resolve()), before["p-project-notes-worker.service"])
        if shutil.which("systemd-analyze"):
            subprocess.run(["systemd-analyze", "--user", "verify", *[str(target / name) for name in before]], check=True)
            # Spaces are valid scalar path bytes; percent signs are specifiers
            # in units and must be escaped in both scalar paths and argv.
            spaced = Path(self.temp.name) / "source with 100% spaces"
            shutil.copytree(SOURCE, spaced, ignore=shutil.ignore_patterns("__pycache__"))
            special_units = Path(self.temp.name) / "special-units"
            subprocess.run([sys.executable, str(spaced / "install.py"), "--no-reload", "--unit-dir", str(special_units)],
                           check=True, stdout=subprocess.DEVNULL)
            subprocess.run(["systemd-analyze", "--user", "verify", *map(str, special_units.glob("*.service"))], check=True)


if __name__ == "__main__":
    unittest.main(verbosity=2)
